### ISSUE TITLE
Geant4 Data Missing

### ISSUE THREAD

**Issue by klendathu2k** [star-bnl/star-spack#1]
After initializing the geant4 environment:
$ module use /cvmfs/star.sdcc.bnl.gov/star-spack/spack/share/spack/modules/linux-rhel7-x86_64
$ module load geant4-10.4.0-gcc-4.8.5-3sqy2u2
$ module load geant4-data-10.4.0-gcc-4.8.5-cnq5bxr

We expect several data directories to be defined:
$ printenv | grep G4

Geant4 throws an exception during initialization which suggests that at least one of these data sets are missing.
And in fact...

$ ls $G4ENSDFSTATEDATA
ls: cannot access /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/g4ensdfstate-2.2-7ebrmv5dpkd7z3cbamjyuqgudh66mpsr/share/data/G4ENSDFSTATE2.2: No such file or directory

These four data sets are not found:
G4ENSDFSTATEDATA, G4LEVELGAMMADATA, G4NEUTRONXSDATA, G4SAIDXSDATA

Expected to be in these directories...
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/g4ensdfstate-
2.2-7ebrmv5dpkd7z3cbamjyuqgudh66mpsr/share/data/G4ENSDFSTATE2.2 /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/g4photonevaporation-5.2-ah6skb7zokeeyd37pgc3wvvprdmbtyl2/share/data/PhotonEvaporation5.2 /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/g4neutronxs-1.4-wl3seozc3c4e7bknp4w7jejx3wnlhusc/share/data/G4NEUTRONXS1.4 /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/g4saiddata-1.1-qtuln36k2b4evqkej2k2r2gthnimkzmn/share/data/G4SAIDDATA1.1

**Comment by klendathu2k** [comment]
This may be helpful... these are the datasets needed for geant4.10

/star/simu/simu/jwebb/G4ENSDFSTATE.2.2.tar.gz
/star/simu/simu/jwebb/G4NEUTRONXS.1.4.tar.gz
/star/simu/simu/jwebb/G4PhotonEvaporation.5.2.tar.gz
/star/simu/simu/jwebb/G4SAIDDATA.1.1.tar.gz

obtained from [here](https://geant4.web.cern.ch/support/download_archive)


(I untarred under the simulations disk, and confirmed that geant4star initializes when environment variables point to these datasets).

**Comment by plexoos** [comment]
Please see if it works now

**Comment by klendathu2k** [comment]
It is working now.  Thanks!
